language: php
php:
  - 7.1
  - 7.2
  - 7.3

install:
  - rm composer.lock
  - composer install --prefer-source

before_script:
 - mkdir -p spec/tmp
 - chmod 777 spec/tmp

script:
- ./vendor/bin/phpspec run --format=pretty --verbose
