language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

install:
  - rm composer.lock
  - composer install --prefer-source

before_script:
 - mkdir -p spec/tmp
 - chmod 777 spec/tmp

script:
- ./vendor/bin/phpspec run --format=pretty --verbose